# Generated by Django 2.0.6 on 2018-06-24 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_auto_20180624_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='imagen',
            new_name='imagenPerfil',
        ),
    ]
