# Generated by Django 2.0.6 on 2018-06-24 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_auto_20180624_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='imagenPerfil',
            new_name='imagen',
        ),
    ]
